events/urls.py
from django.urls import path, register_converter

from . import api, views
from .converters import ApiDateConverter, SlotReferenceConverter

app_name = 'events'

register_converter(ApiDateConverter, 'date')
register_converter(SlotReferenceConverter, 'slot')

urlpatterns = [
    path('', views.EventList.as_view(), name='event-list'),
    path('<pk>/', views.BookEvent.as_view(), name='book-event'),
]

range_api_urlpatterns = [
    path('', api.date_list, name='date-list'),
    path('<date:date>/', api.date_slots, name='date-slots'),
    path('archers/', api.bookable_archers, name='bookable-archers'),
    path('group-booking-info/<slot:slot>/', api.group_booking_info, name='group-booking-info'),
    path('absentable-archers/<slot:slot>/', api.slot_absentable_archers, name='slot-absentable-archers'),
    path(
        'additional-bookable-archers/<slot:slot>/',
        api.slot_additional_bookable_archers,
        name='slot-additional-bookable-archers',
    ),
    # TODO: make book and cancel have slot details in the URL
    path('book/', api.book_slot, name='book-slot'),
    path('cancel/', api.cancel_slot, name='cancel-slot'),
    path('report-absence/<slot:slot>/', api.report_absence, name='report-absence'),
    path('book-in/<slot:slot>/', api.book_in, name='book-in'),
]

tournaments/urls.py
from django.urls import include, path, re_path

from . import api, views

app_name = 'tournaments'

tournament_patterns = [
    path('', views.TournamentDetail.as_view(), name='tournament-detail-old'),
    path('register/', views.TournamentRegistration.as_view(), name='register'),
    path('enter/', views.EntryCreate.as_view(), name='enter'),
    path('entry/<int:pk>/', views.EntryUpdate.as_view(), name='entry-update'),
    path('enter/<int:pk>/delete/', views.EntryDelete.as_view(), name='entry-delete'),
    path('pay/', views.Pay.as_view(), name='pay'),
    path('pay/success/', views.PaymentSuccess.as_view(), name='pay-success'),
]

series_patterns = [
    path('', views.SeriesDetail.as_view(), name='series-detail'),
    path('register/', views.SeriesRegistration.as_view(), name='series-register'),
    path('enter/', views.SeriesEntryCreate.as_view(), name='series-enter'),
    path('pay/', views.SeriesPay.as_view(), name='series-pay'),
    path('pay/success/', views.SeriesPaymentSuccess.as_view(), name='series-pay-success'),
]

tournaments_api_urlpatterns = [
    path('<int:tournament_id>/', api.tournament_info, name='tournament-info'),
]

urlpatterns = [
    path('', views.TournamentList.as_view(), name='home'),
    path('series/<series_slug>/', include(series_patterns)),
    re_path('^(?P<tournament_slug>[a-z0-9]+(?:-[a-z0-9]+)*)/',
            views.TournamentDetail.as_view(), name='tournament-detail'),
    path('old/<tournament_slug>/', include(tournament_patterns)),
]

wallingford_castle/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordResetConfirmView, PasswordResetView,
)
from django.urls import include, path, reverse_lazy

from coaching.urls import coaching_api_urlpatterns
from events.urls import range_api_urlpatterns

from . import views
from .forms import ClientPasswordResetForm, RegisterForm

admin.autodiscover()


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('join/', views.Join.as_view(), name='join'),
    path('juniors/', views.Juniors.as_view(), name='juniors'),
    path('membership-interest/', views.MembershipInterestView.as_view(), name='membership-interest'),
    path('beginners/', include('beginners.urls', namespace='beginners')),
    path('coaching/', include('coaching.urls', namespace='coaching')),
    path('api/coaching/', include((coaching_api_urlpatterns, 'coaching-api'))),
    path('members/', include('membership.urls', namespace='membership')),
    path('members/events/', include('events.urls', namespace='events')),
    path('api/range/', include(range_api_urlpatterns)),
    path('tournaments/', include('tournaments.urls', namespace='tournaments')),
    path('events/', include('bookings.urls', namespace='bookings')),
    path('venues/', include('venues.urls', namespace='venues')),
    # TODO: Style header links
    path('accounts/login/', views.Login.as_view(), name='login'),
    path('accounts/password_reset/', PasswordResetView.as_view(
        form_class=ClientPasswordResetForm,
    ), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        form_class=RegisterForm,
        template_name='registration/register.html',
        success_url=reverse_lazy('membership:overview'),
    ), name='register'),
    path('admin/', admin.site.urls),
    path('webhooks/stripe/', include('payments.urls', namespace='payments')),
    path('', include('courses.urls', namespace='courses')),
]

tournaments/forms.py
from django import forms

from archery.bows import BOWSTYLE_CHOICES
from wallingford_castle.forms import DirectRegisterForm

from .models import Entry


class EntryForm(forms.ModelForm):
    def __init__(self, tournament, **kwargs):
        self.tournament = tournament
        super().__init__(**kwargs)
        self.fields['drugs_consent'].required = True
        self.fields['gdpr_consent'].required = True
        self.fields['bowstyle'].choices = [('', '---------')] + list(
            filter(lambda c: c[0] in self.tournament.bowstyles, BOWSTYLE_CHOICES)
        )
        self.fields['round'].choices = [('', '---------')] + [
            (r.pk, r.name) for r in self.tournament.rounds.all()
        ]
        if len(self.fields['round'].choices) == 2:
            self.fields['round'].choices = [self.fields['round'].choices[-1]]
            self.fields['round'].initial = self.fields['round'].choices[-1][0]
            self.fields['round'].disabled = True
        else:
            self.fields['round'].required = True

    class Meta:
        model = Entry
        fields = [
            'name',
            'agb_number',
            'club',
            'date_of_birth',
            'round',
            'gender',
            'bowstyle',
            'notes',
            'drugs_consent',
            'gdpr_consent',
            'future_event_consent',
        ]

    def save(self, **kwargs):
        self.instance.tournament = self.tournament
        if self.tournament.waiting_list_enabled:
            self.instance.waiting_list = True
        super().save(**kwargs)


class SeriesEntryForm(EntryForm):
    def save(self, **kwargs):
        series = self.tournament
        if series.waiting_list_enabled:
            self.instance.waiting_list = True
        self.instance.series_entry = True
        for tournament in series.tournament_set.all():
            self.instance.pk = None
            self.instance.tournament = tournament
            self.instance.save()
        super(forms.ModelForm, self).save(**kwargs)


class RegisterForm(DirectRegisterForm):

    def save(self):
        user = super().save()
        user.tournament_only = True
        user.save()
        return user

tournaments/views.py
import json

from django.conf import settings
from django.contrib.auth import login
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.views.generic import (
    CreateView, DeleteView, FormView, TemplateView, UpdateView, View,
)

import requests
import stripe
from braces.views import LoginRequiredMixin, MessageMixin

from events.models import Event
from membership.models import Member
from payments.models import Checkout

from .forms import EntryForm, RegisterForm, SeriesEntryForm
from .models import Entry, Series, Tournament


class TournamentList(TemplateView):
    template_name = 'tournaments/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        now = timezone.now()
        context['upcoming_tournaments'] = Tournament.objects.filter(series__isnull=True, date__gt=now).order_by('date')
        context['upcoming_series'] = Series.objects.filter(date__gt=now).order_by('date')
        context['past_tournaments'] = Tournament.objects.filter(date__lte=now).order_by('-date')
        context['bookable_events'] = Event.objects.filter(bookable=True, date__gt=now).order_by('date')
        return context


class TournamentMixin():
    def get_tournament(self):
        return get_object_or_404(Tournament, slug=self.kwargs['tournament_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        self.tournament = self.get_tournament()
        context['tournament'] = self.tournament
        return context


class TournamentDetail(TournamentMixin, TemplateView):
    template_name = 'tournaments/tournament_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['enter_url'] = reverse('tournaments:enter', kwargs={
            'tournament_slug': self.tournament.slug,
        })
        context['register_url'] = reverse('tournaments:register', kwargs={
            'tournament_slug': self.tournament.slug,
        })
        context['payment_url'] = reverse('tournaments:pay', kwargs={
            'tournament_slug': self.tournament.slug,
        })
        if self.request.user.is_authenticated:
            context['existing_entries'] = self.request.user.entry_set.filter(
                tournament=self.tournament,
                series_entry=False,
            )
            context['series_entries'] = self.request.user.entry_set.filter(
                tournament=self.tournament,
                series_entry=True,
            )
            context['to_pay'] = self.request.user.entry_set.filter(
                paid=False,
                waiting_list=False,
                series_entry=False,
                tournament=self.tournament,
            ).count() * self.tournament.entry_fee
            context['entry_form'] = EntryForm(tournament=self.tournament)
            if not self.request.user.tournament_only:
                context['members'] = Member.objects.managed_by(self.request.user)
        else:
            context['register_form'] = RegisterForm()
        return context


class TournamentRegistration(TournamentMixin, FormView):
    template_name = 'tournaments/register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        return self.get_tournament().get_absolute_url()


class EntryCreate(LoginRequiredMixin, TournamentMixin, MessageMixin, CreateView):
    template_name = 'tournaments/entry_form.html'
    model = Entry
    form_class = EntryForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['tournament'] = self.get_tournament()
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        if form.tournament.waiting_list_enabled:
            self.messages.success('Entry added to waiting list. We hope to be in touch soon!')
        else:
            self.messages.success('Entry added, please pay below.')
        response = super().form_valid(form)
        data = json.dumps({
            'icon_emoji': ':wave:',
            'text': 'New entry received for %s to %s!%s\n%s' % (
                form.instance.name,
                form.instance.tournament,
                ' (waiting list)' if form.instance.tournament.waiting_list_enabled else '',
                self.request.build_absolute_uri(
                    reverse(
                        'admin:tournaments_entry_change',
                        args=(form.instance.pk,),
                    )
                ),
            )
        })
        try:
            requests.post(settings.SLACK_TOURNAMENT_HREF, data=data)
        except Exception:
            pass
        return response

    def get_success_url(self):
        return self.get_tournament().get_absolute_url()


class EntryUpdate(LoginRequiredMixin, TournamentMixin, MessageMixin, UpdateView):
    template_name = 'tournaments/entry_form.html'
    model = Entry
    fields = [
        'name',
        'agb_number',
        'club',
        'date_of_birth',
        'gender',
        'bowstyle',
        'notes',
        'drugs_consent',
        'gdpr_consent',
        'future_event_consent',
    ]

    def get_object(self):
        obj = super().get_object()
        if not obj.user == self.request.user:
            raise Http404
        return obj

    def get_success_url(self):
        return self.get_tournament().get_absolute_url()


class EntryDelete(LoginRequiredMixin, TournamentMixin, DeleteView):
    model = Entry

    def get_object(self):
        obj = super().get_object()
        if not obj.user == self.request.user:
            raise Http404
        return obj

    def get_success_url(self):
        return self.get_tournament().get_absolute_url()


class Pay(LoginRequiredMixin, TournamentMixin, MessageMixin, View):
    def get_entries(self, event):
        return self.request.user.entry_set.filter(
            paid=False,
            waiting_list=False,
            tournament=event,
            series_entry=False,
        )

    def get_event(self):
        return self.get_tournament()

    def get_success_url(self, event):
        return reverse('tournaments:pay-success', kwargs={
            'tournament_slug': event.slug,
        })

    def create_intents(self, stripe_id, entries):
        intent = Checkout.objects.create(stripe_id=stripe_id, user=self.request.user)
        for entry in entries:
            intent.lineitemintent_set.create(item=entry)

    def get(self, request, *args, **kwargs):
        event = self.get_event()
        customer_id = self.request.user.customer_id or None
        entries_to_pay_for = self.get_entries(event)
        if not entries_to_pay_for:
            self.messages.error('You have no entries to pay for.')
            return redirect(event.get_absolute_url())
        session = stripe.checkout.Session.create(
            line_items=[{
                'price_data': {
                    'currency': 'gbp',
                    'product_data': {
                        'name': '%s entry to %s' % (entry, event),
                    },
                    'unit_amount': event.entry_fee * 100,
                },
                'quantity': 1,
            } for entry in entries_to_pay_for],
            mode='payment',
            customer=customer_id,
            customer_email=None if customer_id else self.request.user.email,
            customer_creation=None if customer_id else 'always',
            success_url=request.build_absolute_uri(self.get_success_url(event)),
            cancel_url=request.build_absolute_uri(event.get_absolute_url()),
        )
        self.create_intents(stripe_id=session.id, entries=entries_to_pay_for)
        return redirect(session.url, status_code=303)


class PaymentSuccess(LoginRequiredMixin, TournamentMixin, TemplateView):
    template_name = 'tournaments/payment_success.html'

    def get_event(self):
        return self.get_tournament()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tournament'] = self.get_event()
        return context


class SeriesMixin():
    def get_series(self):
        return get_object_or_404(Series, slug=self.kwargs['series_slug'])

    def get_tournament(self):
        # Easiest to just force overrride this as get_tournament will never work.
        return self.get_series()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        self.tournament = self.series = self.get_series()
        context['tournament'] = self.tournament
        return context


class SeriesDetail(SeriesMixin, TemplateView):
    template_name = 'tournaments/tournament_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['enter_url'] = reverse('tournaments:series-enter', kwargs={
            'series_slug': self.series.slug,
        })
        context['register_url'] = reverse('tournaments:series-register', kwargs={
            'series_slug': self.series.slug,
        })
        context['payment_url'] = reverse('tournaments:series-pay', kwargs={
            'series_slug': self.series.slug,
        })
        if self.request.user.is_authenticated:
            context['entry_form'] = EntryForm(tournament=self.series)
            if not self.request.user.tournament_only:
                context['members'] = Member.objects.managed_by(self.request.user)
            context['series_entries'] = self.request.user.entry_set.filter(
                tournament__series=self.series,
                series_entry=True,
            ).distinct('agb_number')
            context['to_pay'] = self.request.user.entry_set.filter(
                paid=False,
                waiting_list=False,

tournaments/templates/tournaments/entry_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="flex-sections">
    <section>
        <p>Are you sure you want to remove the entry for {{ entry }}?</p>
        {% if entry.paid %}
        <p>Please contact the tournament organiser to arrange a refund.</p>
        {% endif %}
        <form class="form" method="POST" action=".">
            {% csrf_token %}
            <input type="submit" value="Confirm" class="btn">
        </form>
    </section>
</div>
{% endblock %}

tournaments/templates/tournaments/entry_form.html
{% extends 'base.html' %}

{% block content %}
<div class="flex-sections">
    <section>
        {% if object %}
        <h2>Update entry details</h2>
        {% else %}
        <h2>Add entry</h2>
        {% endif %}
        <form class="form page-form" method="POST" action=".">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="{% if object %}Save details{% else %}Enter{% endif %}" class="btn">
        </form>
    </section>
</div>
{% endblock %}

tournaments/templates/tournaments/home.html
{% extends 'base.html' %}

{% block og_image %}scoring{% endblock %}

{% block hero %}
<div class="hero hero--tournaments-list">
    <h1>Tournaments</h1>
</div>
{% endblock %}

{% block content %}
<div class="flex-sections">
    <section>
        <h2>Upcoming open tournaments</h2>
        <p>
        We look forwards to welcoming you to Wallingford Castle Archers for a
        tournament.
        </p>
        {% for tournament in upcoming_tournaments %}
        <h3>{{ tournament }}</h3>
        <p><strong>{{ tournament.date|date:"jS F Y" }}</strong></p>
        <p>
        {% for round in tournament.labelled_rounds %}
        {{ round }}
        {% if not forloop.last %}<br />{% endif %}
        {% endfor %}
        </p>
        <a href="{{ tournament.get_absolute_url }}" class="btn">Find out more</a>
        {% endfor %}

        {% for series in upcoming_series %}
        <h3>{{ series }}</h3>
        <p><strong>Starting {{ series.date|date:"jS F Y" }}</strong></p>
        {{ series.event_format|linebreaks }}
        <a href="{{ series.get_absolute_url }}" class="btn">Find out more</a>
        {% endfor %}

        {% if not upcoming_tournaments and not upcoming_series %}
        <p>
        We don't have any future shoots confirmed yet, but watch this space and
        follow us on
        <a href="https://www.facebook.com/wallingfordcastlearchers/">Facebook</a>
        to find out first when we open entries.
        {% endif %}
    </section>
    <section class="double">
        <h2>Past open tournaments</h2>
        <p>
        Wallingford Castle Archers run a wide range of open Tournaments, aimed
        at a range of ages and abilities. We also run events on behalf of
        Oxfordshire and Archery GB.
        </p>
        {% for tournament in past_tournaments %}
        {% ifchanged tournament.date.year %}
        <h3>{{ tournament.date.year }}</h3>
        {% endifchanged %}
        <dt class="inline">{{ tournament.date|date:"jS F" }}</dt>
        <dd class="inline"><a href="{{ tournament.get_absolute_url }}">{{ tournament }}</a></dd>
        <br>
        {% endfor %}
        </ul>
    </section>
</div>
{% endblock %}

tournaments/templates/tournaments/payment_success.html
{% extends 'base.html' %}

{% block content %}
<div class="flex-sections">
    <section>
        <h2>{{ tournament }}</h2>
        <p>Payment recieved, thank you!</p>
        <p>
        The Target List and final information will be distributed in the
        week before the event.
        </p>
        <p>
        If you have any problems, please contact the tournament organisers at
        <a href="mailto:{{ tournament.tournament_organiser_email }}">
            {{ tournament.tournament_organiser_email }}
        </a>.
        </p>
        <p>
        <a class="btn" href="{{ tournament.get_absolute_url }}">< Back to event</a>
        </p>
    <section>
</div>
{% endblock %}

tournaments/templates/tournaments/register.html
{% extends 'base.html' %}

{% block content %}
    <h2>Welcome to Wallingford Castle Archers!</h2>
    <form class="form" method="POST" action=".">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn">
    </form>
{% endblock %}

tournaments/templates/tournaments/tournament_detail.html
{% extends 'base.html' %}

{% block og_image %}{% if tournament.indoors %}indoors{% else %}outdoors{% endif %}{% endblock %}

{% block hero %}
<div class="hero hero--short hero--tournaments-{% if tournament.indoors %}indoor{% else %}outdoor{% endif %}">
    <h1>{{ tournament }}</h1>
</div>
{% endblock %}

{% block content %}
<div class="tournament-enter-block" id="app-tournament-entry" data-tournament="{{ tournament.pk }}">
    <h3 class="no-border">Entry is open</h3>
    <a class="btn">Enter</a>
</div>
<div class="flex-sections tournament-prospectus">
    <section>
        <h2>Prospectus</h2>

        {% if not tournament.is_series %}
        <h3>Date</h3>
        <p>
        {{ tournament.date|date:"jS F Y" }}
        </p>
        {% endif %}

        {% if tournament.series %}
        <p>This event is a part of <strong><a href="{{ tournament.series.get_absolute_url }}">{{ tournament.series }}</a></strong>. Enter all events for a discount!</p>
        {% elif tournament.is_series %}
        <p>This is a series of events through the season. Enter all events here for a discount, or enter individual events with the links below.</p>
        <h3>Events</h3>
        {% for t in tournament.ordered_tournaments %}
        <dt>{{ t.date|date:"jS F" }}</dt>
        <dd><a href="{{ t.get_absolute_url }}">{{ t }}</a></dd>
        {% endfor %}
        {% endif %}

        <h3>Event Format</h3>
        <p>
        {% for round in tournament.labelled_rounds %}
        <strong>{{ round }}</strong>
        {% if not forloop.last %}<br />{% endif %}
        {% endfor %}
        </p>
        {{ tournament.event_format|linebreaks }}

        <h3>Timing</h3>
        {{ tournament.timing|linebreaks }}

        <h3>Judges</h3>
        {{ tournament.judges|linebreaks }}

        <h3>Tournament Organiser</h3>
        <p><a href="mailto:{{ tournament.tournament_organiser_email }}">{{ tournament.tournament_organiser }}</a></p>
    </section>

    <section>
        <h2>Rules</h2>

        <h3>Awards</h3>
        {{ tournament.awards|linebreaks }}

        <h3>Dress</h3>
        {{ tournament.dress|linebreaks }}

        <h3>Drug testing</h3>
        {{ tournament.drug_testing|linebreaks }}
    </section>

    <section>
        <h2>Logistics</h2>
        <h3>Venue</h3>
        {{ tournament.venue_description|linebreaks }}
        <iframe
            width="100%"
            height="300"
            frameborder="0" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDGuvasiOAUbxa4w_xoZ8YaY38M9Vpz2Ec&q={{ tournament.venue_google_search }}&zoom=14" allowfullscreen>
        </iframe>
        <h3>Refreshments</h3>
        {{ tournament.refreshments|linebreaks }}
	{% if tournament.camping %}
	    <h3>Camping</h3>
	    {{ tournament.camping|linebreaks }}
	{% endif %}
    </section>
    <section>
        {% if tournament.entry_is_open %}
        <h2>Enter now</h2>
        {% elif tournament.is_future %}
        <h2>Entry information</h2>
        {% else %}
        <h2>Results</h2>
        {% endif %}

        {% if tournament.tamlynscore_id %}
        {% if tournament.is_future %}
        <p><a class="btn" href="https://tamlynscore.co.uk/tournaments/{{ tournament.tamlynscore_id }}/target-list/">View Target List</a></p>
        {% else %}
        <p><a class="btn" href="https://tamlynscore.co.uk/tournaments/{{ tournament.tamlynscore_id }}/results/by-round/html/">Results on TamlynScore</a></p>
        {% endif %}
        {% endif %}

        {% if tournament.full_results_document %}
        <p><a class="btn" href="{{ tournament.full_results_document|safe }}">Full results document</a></p>
        {% endif %}

        {% if tournament.is_future %}
        {{ tournament.entry_information|linebreaks }}

        <p>
            If you are having problems entering, please contact the <a href="mailto:{{ tournament.tournament_organiser_email }}">Tournament Organiser</a>.
        </p>
        <p>
        Entry fee is £{{ tournament.entry_fee }}.
        {% if tournament.entry_will_open %}
        Entries will open on {{ tournament.entries_open|date:"jS F Y" }} at {{ tournament.entries_open|date:"H:i" }}.
        {% elif tournament.entry_is_open %}
        Entries must be received by {{ tournament.entries_close|date:"jS F Y" }} at {{ tournament.entries_close|date:"H:i" }}.
        {% endif %}
        </p>
        {% endif %}

        {% if existing_entries or series_entries %}
            <h3>Entries</h3>
            <ul>
                {% for entry in existing_entries %}
                <li>
                    <strong>{{ entry.name }}</strong>
                    {% if entry.waiting_list %}
                    On waiting list
                    {% endif %}
                    {% if entry.paid %}
                    Paid
                    {% endif %}
                    {% if not tournament.series and not tournament.is_series %}
                        <a href="{% url 'tournaments:entry-update' tournament_slug=tournament.slug pk=entry.pk %}">Edit</a>
                        {% if not entry.paid %}
                        <a href="{% url 'tournaments:entry-delete' tournament_slug=tournament.slug pk=entry.pk %}">Remove</a>
                        {% endif %}
                    {% endif %}
                </li>
                {% endfor %}

                {% for entry in series_entries %}
                <li>
                    <strong>{{ entry.name }}</strong>
                    Entered for the whole series.
                    {% if not entry.paid and not tournament.is_series %}
                    <br><a href="{{ entry.tournament.series.get_absolute_url }}">Pay via series page.</a>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
            {% if to_pay %}
            {% if not user.subscription_id %}
            <p>To pay: £{{ to_pay }}</p>
            <a href="{{ payment_url }}" class="btn">Pay now</a>
            <p><small>
            Payments are processed securely using Stripe. Wallingford Castle Archers does
            not store your credit card details. If you have any problems, please
            contact the tournament organiser. Payment can be accepted via cheque or
            BACS on request. Charges will be shown on your account as WALLINGFORD
            C. ARCHERS.
            </small></p>
            {% else %}
            <p>Tournament fees will be added to your membership payments.</p>
            {% endif %}
            {% endif %}
        {% endif %}

        {% if tournament.is_future and tournament.waiting_list_enabled %}
            <p><strong>
                We are now operating a waiting list. You may enter your details
                below but will not be able to pay. If we are able to offer you
                a space due to capacity on your choice of round or
                cancellations, we will be in touch and you can return here to
                pay. Thank you for your patience and rest assured we will do
                our best to accommodate you.
            </strong></p>
        {% elif tournament.is_future and not tournament.entry_is_open and not tournament.entry_will_open %}
            <p><strong>
                The competition is now full. Please contact the
                <a href="mailto:{{ tournament.tournament_organiser_email }}">Tournament Organiser</a> to
                be added to a waiting list.
            </strong></p>
        {% endif %}

        {% if tournament.entry_is_open %}
            {% if user.is_authenticated %}
            <form id="tournament-entry" class="form page-form" action="{{ enter_url }}" method="POST">
                <h2>Add entry</h2>
                {% if members %}
                <div class="member-select">
                    {% for member in members %}
                    <p>
                    <a class="btn"
                        data-name="{{ member.archer.name }}"
                        data-agb="{{ member.archer.agb_number }}"
                        data-dob="{{ member.archer.date_of_birth|date:"d/m/Y" }}"
                    >{{ member }}</a>
                    </p>
                    {% endfor %}
                    <p><a class="btn">Another archer</a></p>
                </div>
                {% endif %}
                <div class="form">
                    {% csrf_token %}
                    {{ entry_form }}
                    <input type="submit" value="Enter" class="btn">
                </div>
            </form>
            {% else %}
            <form class="form page-form" action="{{ register_url }}" method="POST">
                <h2>Register account</h2>
                {% csrf_token %}
                {{ register_form }}
                <input type="submit" value="Register" class="btn">
            </form>
            <p><a href="{% url 'login' %}">Login to existing account</a></p>
            {% endif %}
        {% endif %}
    </section>
</div>
{% endblock %}