courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('holidays/', views.Holidays.as_view(), name='holidays'),
    path('holidays/book/', views.HolidaysBook.as_view(), name='holidays-book'),
    path('holidays/pay/', views.HolidaysPay.as_view(), name='holidays-payment'),
    path('dgs/', views.SchoolSignup.as_view(school='dgs'), name='dgs'),
    path('sbs/', views.SchoolSignup.as_view(school='sbs'), name='sbs'),
    path('maiden-erlegh/', views.SchoolSignup.as_view(school='maiden-erlegh'), name='maiden-erlegh'),
    # path('icknield/', views.SchoolSignup.as_view(school='icknield'), name='icknield'),
    # path('home-ed/', views.SchoolSignup.as_view(school='home-ed'), name='home-ed'),
    path('juniors/minis/', views.MinisInterestView.as_view(), name='minis-interest'),
    path('members/courses/', views.MembersCourseList.as_view(), name='members-course-list'),
    path('members/courses/external/', views.NonMembersCourseList.as_view(), name='non-members-course-list'),
    path('members/courses/<pk>/book/', views.MembersCourseBooking.as_view(), name='members-course-booking'),
    path(
        'members/courses/external/<pk>/book/',
        views.NonMembersCourseBooking.as_view(),
        name='non-members-course-booking',
    ),
    path('members/courses/pay/', views.NonMembersPayment.as_view(), name='non-members-payment'),
]

events/urls.py
from django.urls import path, register_converter

from . import api, views
from .converters import ApiDateConverter, SlotReferenceConverter

app_name = 'events'

register_converter(ApiDateConverter, 'date')
register_converter(SlotReferenceConverter, 'slot')

urlpatterns = [
    path('', views.EventList.as_view(), name='event-list'),
    path('<pk>/', views.BookEvent.as_view(), name='book-event'),
]

range_api_urlpatterns = [
    path('', api.date_list, name='date-list'),
    path('<date:date>/', api.date_slots, name='date-slots'),
    path('archers/', api.bookable_archers, name='bookable-archers'),
    path('group-booking-info/<slot:slot>/', api.group_booking_info, name='group-booking-info'),
    path('absentable-archers/<slot:slot>/', api.slot_absentable_archers, name='slot-absentable-archers'),
    path(
        'additional-bookable-archers/<slot:slot>/',
        api.slot_additional_bookable_archers,
        name='slot-additional-bookable-archers',
    ),
    # TODO: make book and cancel have slot details in the URL
    path('book/', api.book_slot, name='book-slot'),
    path('cancel/', api.cancel_slot, name='cancel-slot'),
    path('report-absence/<slot:slot>/', api.report_absence, name='report-absence'),
    path('book-in/<slot:slot>/', api.book_in, name='book-in'),
]

venues/urls.py
from django.urls import path

from . import views

app_name = 'venues'


urlpatterns = [
    path('', views.VenueList.as_view(), name='index'),
    path('<slug:slug>/', views.VenueDetail.as_view(), name='detail'),
]

wallingford_castle/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordResetConfirmView, PasswordResetView,
)
from django.urls import include, path, reverse_lazy

from coaching.urls import coaching_api_urlpatterns
from events.urls import range_api_urlpatterns

from . import views
from .forms import ClientPasswordResetForm, RegisterForm

admin.autodiscover()


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('join/', views.Join.as_view(), name='join'),
    path('juniors/', views.Juniors.as_view(), name='juniors'),
    path('membership-interest/', views.MembershipInterestView.as_view(), name='membership-interest'),
    path('beginners/', include('beginners.urls', namespace='beginners')),
    path('coaching/', include('coaching.urls', namespace='coaching')),
    path('api/coaching/', include((coaching_api_urlpatterns, 'coaching-api'))),
    path('members/', include('membership.urls', namespace='membership')),
    path('members/events/', include('events.urls', namespace='events')),
    path('api/range/', include(range_api_urlpatterns)),
    path('tournaments/', include('tournaments.urls', namespace='tournaments')),
    path('events/', include('bookings.urls', namespace='bookings')),
    path('venues/', include('venues.urls', namespace='venues')),
    # TODO: Style header links
    path('accounts/login/', views.Login.as_view(), name='login'),
    path('accounts/password_reset/', PasswordResetView.as_view(
        form_class=ClientPasswordResetForm,
    ), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        form_class=RegisterForm,
        template_name='registration/register.html',
        success_url=reverse_lazy('membership:overview'),
    ), name='register'),
    path('admin/', admin.site.urls),
    path('webhooks/stripe/', include('payments.urls', namespace='payments')),
    path('', include('courses.urls', namespace='courses')),
]

courses/views.py
import datetime
import json

from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Prefetch, Q
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView, FormView, ListView, TemplateView, View,
)
from django.views.generic.detail import SingleObjectMixin

import requests
import stripe
from braces.views import MessageMixin
from dateutil.relativedelta import relativedelta

from membership.models import Member
from payments.models import Checkout
from wallingford_castle.forms import DirectRegisterForm
from wallingford_castle.mixins import FullMemberRequired
from wallingford_castle.models import Archer

from .forms import (
    CourseInterestForm, MembersBookCourseForm, NonMembersBookCourseForm,
    SessionBookingForm,
)
from .models import Attendee, Course, Session


class Holidays(TemplateView):
    template_name = 'courses/holidays.html'


class HolidaysUtils:
    def dispatch(self, request, *args, **kwargs):
        try:
            self.course = Course.objects.get(can_book_individual_sessions=True, open_for_bookings=True)
        except Course.DoesNotExist:
            self.messages.error('Bookings are not currently open, sorry. Please contact us for more information.')
            return redirect('courses:holidays')
        return super().dispatch(request, *args, **kwargs)

    def get_members(self):
        return Member.objects.managed_by(self.request.user).filter(archer__age='junior').select_related('archer')

    def get_archers(self, members):
        member_archers = [member.archer for member in members]
        other_archers = Archer.objects.filter(
            Q(user=self.request.user) | Q(managing_users=self.request.user),
            age='junior',
        ).exclude(id__in=[archer.pk for archer in member_archers])
        return other_archers

    def annotate_with_details(self, archer, errored_booking_forms=None):
        if errored_booking_forms is None:
            errored_booking_forms = {}
        try:
            archer.attendee = archer.attendee_set.get(course=self.course)
            archer.sessions_booked = archer.attendee.session_set.order_by('session__start_time')
            archer.booking_form = errored_booking_forms.get(
                str(archer.pk),
                SessionBookingForm(course=self.course, booked=archer.sessions_booked, prefix=archer.pk),
            )
        except Attendee.DoesNotExist:
            archer.attendee = None
            archer.booking_form = SessionBookingForm(course=self.course, prefix=archer.pk)
        return archer

    def get_to_pay(self, archers, members):
        to_pay = 0
        sessions = []
        for archer in archers:
            if archer.attendee:
                for session in archer.sessions_booked:
                    if not session.paid:
                        sessions.append(session)
                        to_pay += session.fee
        for member in members:
            if member.archer.attendee:
                for session in member.archer.sessions_booked:
                    if not session.paid:
                        sessions.append(session)
                        to_pay += session.fee
        return sessions, to_pay


class HolidaysBook(HolidaysUtils, MessageMixin, TemplateView):
    template_name = 'courses/holidays-book.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_anonymous:
            context.setdefault('login_form', AuthenticationForm())
            context.setdefault('register_form', DirectRegisterForm())
        else:
            context['members'] = self.get_members()
            context['archers'] = self.get_archers(context['members'])

            for member in context['members']:
                member.archer = self.annotate_with_details(member.archer, context.get('errored_booking_forms'))
            for archer in context['archers']:
                self.annotate_with_details(archer, context.get('errored_booking_forms'))

            form = CourseInterestForm(initial={'contact_email': self.request.user.email}, course_type='holidays')
            context.setdefault('new_archer_form', form)

            _, context['to_pay'] = self.get_to_pay(context['archers'], context['members'])
            context['STRIPE_KEY'] = settings.STRIPE_KEY

        return context

    def post(self, request, *args, **kwargs):
        context = {}
        form = request.POST.get('form')
        if form == 'login':
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                login(request, form.user_cache)
                return self.get(request, *args, **kwargs)
            else:
                context['login_form'] = form
        elif form == 'register':
            form = DirectRegisterForm(data=request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                return self.get(request, *args, **kwargs)
            else:
                context['register_form'] = form
        elif form == 'new-archer':
            form = CourseInterestForm(data=request.POST, course_type='holidays')
            if form.is_valid():
                today = datetime.date.today()
                age = relativedelta(today, form.instance.date_of_birth).years
                if age >= 13:
                    msg = (
                        'Holiday archery is only available for under 13s. For '
                        'older children, please book a beginners course.'
                    )
                    form.add_error(None, msg)
                    context['new_archer_form'] = form
                else:
                    interest = form.save()
                    interest.convert_to_archer(self.request.user)
                    return self.get(request, *args, **kwargs)
            else:
                context['new_archer_form'] = form
        elif form == 'booking':
            archer_id = request.POST['archer']
            form = SessionBookingForm(data=request.POST, course=self.course, prefix=archer_id)
            if form.is_valid():
                try:
                    form.save(archer_id=archer_id)
                    return self.get(request, *args, **kwargs)
                except SessionBookingForm.CancellationException:
                    msg = (
                        'To cancel a session which has been paid for, please '
                        'email us at hello@wallingfordcastle.co.uk'
                    )
                    form.add_error(None, msg)
                    context['errored_booking_forms'] = {archer_id: form}
        elif form == 'add-to-subscription':
            if self.request.user.subscription_id:
                members = self.get_members()
                archers = self.get_archers(members)
                for member in members:
                    member.archer = self.annotate_with_details(member.archer)
                for archer in archers:
                    self.annotate_with_details(archer)
                description = 'Holiday archery'
                _, amount = self.get_to_pay(archers, members)
                self.request.user.add_invoice_item(
                    amount=amount * 100,
                    description=description,
                )
                for member in members:
                    for session in getattr(member.archer, 'sessions_booked', []):
                        session.paid = True
                        session.save()
                for archer in archers:
                    for session in getattr(archer, 'sessions_booked', []):
                        session.paid = True
                        session.save()
                self.messages.success(
                    'Thanks for booking your holiday session! We will contact you '
                    'soon with more details.'
                )
            else:
                self.messages.error('You do not seem to have an active membership.')
        return self.render_to_response(context=self.get_context_data(**context))


class HolidaysPay(HolidaysUtils, MessageMixin, View):
    def get(self, request, *args, **kwargs):
        customer_id = self.request.user.customer_id or None
        return_url = reverse('courses:holidays')
        members = self.get_members()
        archers = self.get_archers(members)
        for archer in archers:
            self.annotate_with_details(archer)
        to_pay, _ = self.get_to_pay(archers, members)
        if not to_pay:
            self.messages.error('You have no sessions to pay for.')
            return redirect(return_url)
        stripe_session = stripe.checkout.Session.create(
            line_items=[{
                'price_data': {
                    'currency': 'gbp',
                    'product_data': {
                        'name': 'Holiday archery session - %s on %s' % (
                            session.attendee.archer,
                            session.session.start_time.date().strftime('%-d %B %Y'),
                        ),
                    },
                    'unit_amount': session.fee * 100,
                },
                'quantity': 1,
            } for session in to_pay],
            mode='payment',
            customer=customer_id,
            customer_email=None if customer_id else self.request.user.email,
            customer_creation=None if customer_id else 'always',
            success_url=request.build_absolute_uri(return_url),
            cancel_url=request.build_absolute_uri(return_url),
        )
        intent = Checkout.objects.create(stripe_id=stripe_session.id, user=self.request.user)
        for session in to_pay:
            intent.lineitemintent_set.create(item=session)
        return redirect(stripe_session.url, status_code=303)

courses/templates/courses/dgs.html
{% extends 'base.html' %}

{% block content %}
<div class="flex-sections">
    <section>
        <h2>Didcot Girls School</h2>
        <p>Wallingford Castle Archers are pleased to be working with Didcot Girls School to offer an after school archery club. We meet in the Sports Hall during the winter and on the school field in the summer.</p>
        <p>We are currently running on Mondays between 3:30 and 4:30pm. The cost is £60 per term, payable in advance.</p>
    </section>
    <section>
        <h3>Register Interest</h3>
        <p>We will be in touch when we have space to accommodate you.</p>
        <form class="form page-form" method="POST" action=".">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn" value="Register">
        </form>
    </section>
</div>
{% endblock %}

courses/templates/courses/holidays-book.html
{% extends 'base.html' %}

{% block hero %}
<div class="hero hero--targets">
    <h1>Holiday archery</h1>
</div>
{% endblock %}

{% block content %}
<p><a href="{% url 'courses:holidays' %}">< Back to information</a></p>
<h2>Booking</h2>
<p>To book holiday sessions, please first register a new participant. You can then select sessions and pay for them.</p>
{% if user.is_anonymous %}
<div class="flex-sections">
    <section>
        <h2>Log into existing account</h2>
        <form class="form page-form" method="POST" action="{% url 'courses:holidays-book' %}">
            <input type="hidden" name="form" value="login" />
            {% csrf_token %}
            {{ login_form }}
            <input type="submit" class="btn">
        </form>
    </section>
    <section>
        <h2>Create new account</h2>
        <form class="form page-form" method="POST" action="{% url 'courses:holidays-book' %}">
            <input type="hidden" name="form" value="register" />
            {% csrf_token %}
            {{ register_form }}
            <input type="submit" class="btn">
        </form>
    </section>
</div>
{% else %}
<div class="flex-sections">
    {% if to_pay %}
    <section>
        <h2>Pay for outstanding sessions</h2>
        <p>You have a total of £{{ to_pay }} to pay</p>
        {% if user.subscription_id %}
        <form action="{% url 'courses:holidays-book' %}" method="POST" class="form">
            <input type="hidden" name="form" value="add-to-subscription" />
            {% csrf_token %}
            <input type="submit" value="Add to membership" class="btn" />
            <p><small>The additional fee will go out with your next monthly membership payment</small></p>
        </form>
        {% else %}
        <form action="{% url 'courses:holidays-book' %}" method="POST" class="form">
            <a href="{% url 'courses:holidays-payment' %}" class="btn">Pay £{{ to_pay }}</a>
        </form>
        {% endif %}
    </section>
    {% endif %}

    {% if members %}
    <section>
        <h2>Book a club member</h2>
        {% for member in members %}
        {% with member.archer as archer %}
        <h3>{{ archer }}</h3>
        {% if archer.attendee %}
            {% if archer.sessions_booked %}
            <p>Currently booked for:</p>
            <ul>
                {% for booking in archer.sessions_booked %}
                <li>{{ booking.session.label }}</li>
                {% endfor %}
            </ul>
            {% else %}
            <p>Not currently booked for any sessions</p>
            {% endif %}
        <form class="form page-form page-form--checkbox" method="POST" action="{% url 'courses:holidays-book' %}">
            <h3>Amend booking</h3>
            <input type="hidden" name="form" value="booking" />
            <input type="hidden" name="archer" value="{{ archer.id }}" />
            {% csrf_token %}
            {{ archer.booking_form }}
            <input type="submit" class="btn">
        </form>
        {% else %}
        <p>Not currently booked for any sessions</p>
        <form class="form page-form page-form--checkbox" method="POST" action="{% url 'courses:holidays-book' %}">
            <h3>Make a booking</h3>
            <input type="hidden" name="form" value="booking" />
            <input type="hidden" name="archer" value="{{ archer.id }}" />
            {% csrf_token %}
            {{ archer.booking_form }}
            <input type="submit" class="btn">
        </form>
        {% endif %}
        {% endwith %}
        {% endfor %}
    </section>
    {% endif %}

    {% if archers %}
    <section>
        <h2>Book an archer</h2>
        {% for archer in archers %}
        <h3>{{ archer }}</h3>
        {% if archer.attendee %}
        <p>Currently booked for:</p>
        <ul>
            {% for booking in archer.sessions_booked %}
            <li>{{ booking.session.label }} {% if booking.paid %}<small>PAID</small>{% endif %}</li>
            {% endfor %}
        </ul>
        <form class="form page-form page-form--checkbox" method="POST" action="{% url 'courses:holidays-book' %}">
            <h3>Amend booking</h3>
            <input type="hidden" name="form" value="booking" />
            <input type="hidden" name="archer" value="{{ archer.id }}" />
            {% csrf_token %}
            {{ archer.booking_form }}
            <input type="submit" class="btn">
        </form>
        {% else %}
        <p>Not currently booked for any sessions</p>
        <form class="form page-form page-form--checkbox" method="POST" action="{% url 'courses:holidays-book' %}">
            <h3>Make a booking</h3>
            <input type="hidden" name="form" value="booking" />
            <input type="hidden" name="archer" value="{{ archer.id }}" />
            {% csrf_token %}
            {{ archer.booking_form }}
            <input type="submit" class="btn">
        </form>
        {% endif %}
        {% endfor %}
    </section>
    {% endif %}

    <section>
        <h2>Add a new archer</h2>
        <form class="form page-form" method="POST" action="{% url 'courses:holidays-book' %}">
            <input type="hidden" name="form" value="new-archer" />
            {% csrf_token %}
            {{ new_archer_form }}
            <input type="submit" class="btn">
        </form>
    </section>
</div>
{% endif %}
{% endblock %}

courses/templates/courses/holidays.html
{% extends 'base.html' %}

{% block hero %}
<div class="hero hero--targets">
    <h1>Holiday archery</h1>
</div>
{% endblock %}

{% block content %}
<div class="flex-sections">
    <section>
        <h2>About</h2>
        <p>
        Over the easter and summer holidays we will be offering a range of
        archery classes for children aged 6-11. Whether you've never held a bow
        before, shoot regularly at minis, school or a leisure centre and want
        to keep practicing over the holidays, or are wanting an opportunity to
        progress your skills, we have the classes for you.
        </p>
        <p>
        All sessions will be run in small groups with an experienced coach.
        Equipment is provided, but if you have your own equipment you can bring
        it along.
        </p>
        <h3>Venue, weather and attire</h3>
        <p>
        All sessions will take place at our outdoor venue -
        <a href="{% url 'venues:index' %}">Wallingford Sports Park</a>. We do of
        course hope for wonderful sunny days, but archery is an all weather
        sport and sessions will continue in light rain. It is important that
        children bring appropriate attire for the conditions - sun cream, coats
        etc. Most importantly, long hair must be tied back and closed toed shoes
        must be worn. We reserve the right to stop children participating if
        their clothing does not allow them to take part safely.
        </p>
        <p><a class="btn" href="{% url 'courses:holidays-book' %}">Book now</a></p>
    </section>
    <section>
        <h2>Groups</h2>
        <p>
        Sessions are aimed at archers aged 6-11. Older children should enquire
        about <a href="{% url 'juniors' %}">arrows sessions</a> for under 16s,
        or <a href="{% url 'beginners:index' %}">beginners
        courses</a>.
        </p>
        <h3>Beginner sessions</h3>
        <p>
        These classes are ideal for children with no or very little previous
        experience of archery. We will cover how to shoot the bow, how to be
        safe on the archery range, and how to score your arrows. Each session
        is self contained and new archers are welcome at any session, but we
        will also be progressing repeat visitors towards their first World
        Archery beginners awards.
        </p>
        <h3>Intermediate sessions</h3>
        <p>
        These classes are ideal for children with some regular recent
        experience of archery. This may be at the club, at their school or at a
        local leisure centre. These coach led sessions will cover a range of
        technique, skills and knowledge about the sport. There will be an
        opportunity to attain World Archery beginners awards.
        </p>
        <p><a class="btn" href="{% url 'courses:holidays-book' %}">Book now</a></p>
    </section>
    <section>
        <h2>Booking</h2>
        <p>
        We understand that many children go on holiday during school breaks,
        and as such every session is self contained. You can book onto as many
        or as few sessions as you like!
        </p>
        <h3>Dates and times</h3>
        <p>
        We plan to follow the same session times each day, and run sessions
        every week throughout the easter and summer holidays. Some dates will
        not be running due to facilities availability and scheduling clashes -
        you can check exact times and dates on the booking page.
        </p>
        <p>Session times:</p>
        <ul>
            <li>Wednesdays 3-3:45pm: Beginners session</li>
            <li>Wednesdays 3:45-4:30pm: Intermediates session</li>
            <li>Sundays 12:30-1:15pm: Beginners session</li>
            <li>Sundays 1:15-2:30pm: Intermediates session</li>
        </ul>
        <h3>Cost</h3>
        <p>
        Sessions are priced at £10 for non-members and £5 for members. Please
        note that there is a maximum allowance of six sessions as a non-member
        in a year before you have to join the club. This is for insurance
        reasons. <a href="{% url 'join' %}">Find out more about membership</a>.
        </p>
        <p><a class="btn" href="{% url 'courses:holidays-book' %}">Book now</a></p>
    </section>
</div>
{% endblock %}

courses/templates/courses/home-ed.html
{% extends 'base.html' %}

{% block content %}
<div class="flex-sections">
    <section>
        <h2>Home Educated minis</h2>
        <p>Wallingford Castle Archers are pleased to be offering archery classes for home educated children. The classes will take place at Wallingford Sports Park, OX10 9RB.</p>
        <p>Sessions will be running on Thursdays at 14:00.</p>
        <p>We are running on the following dates:</p>
        <ul>
            <li>25th April</li>
            <li>2nd May</li>
            <li>9th May</li>
            <li>16th May</li>
            <li>23rd May</li>
            <li><em>No session 30th May</em></li>
            <li>6th June</li>
            <li>13th June</li>
            <li>20th June</li>
            <li><em>No session 28th June</em></li>
            <li>4th July</li>
            <li>11th July</li>
            <li>18th July</li>
        </ul>
        <p>The cost for this term is £66, payable in advance.</p>
    </section>
    <section>
        <h3>Book</h3>
        <form class="form page-form" method="POST" action=".">
            <p>To register for the course, please complete the form below.</p>
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn" value="Register">
        </form>
    </section>
</div>
{% endblock %}

courses/templates/courses/icknield.html
{% extends 'base.html' %}

{% block content %}
<div class="flex-sections">
    <section>
        <h2>Icknield Community College</h2>
        <p>Wallingford Castle Archers are pleased to be working with Icknield Community College to offer an after school archery club.</p>
        <p>Sessions will be running after school on Wednesdays on the following dates:</p>
        <ul>
            <li>09/01/19</li>
            <li>16/01/19</li>
            <li>23/01/19</li>
            <li>30/01/19</li>
            <li>06/02/19</li>
            <li>13/02/19</li>
            <li><em>Nothing 20/02/19 - half term</em></li>
            <li>27/02/19</li>
            <li>06/03/19</li>
            <li>13/03/19</li>
            <li><em>Nothing 20/03/19 - drama production</em></li>
            <li>27/03/19</li>
            <li>03/04/19</li>
        </ul>
        <p>The cost for this term is £55, payable in advance.</p>
    </section>
    <section>
        <h3>Book</h3>
        <form class="form page-form" method="POST" action=".">
            <p>To register for the course, please complete the form below.</p>
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn" value="Register">
        </form>
    </section>
</div>
{% endblock %}

courses/templates/courses/members_book_course.html
{% extends 'base.html' %}

{% block content %}
<p><a href="{% url 'courses:members-course-list' %}">< Back to course list</a></p>
<h2>{{ course }}</h2>
{{ course.description|linebreaks }}
<h4>Dates</h4>
<ul>
    {% for session in course.session_set.all %}
    <li>{{ session.start_time }}</li>
    {% endfor %}
</ul>
<h4>Book</h4>
<p>Course cost: £{{ course.members_price }}</p>
<form class="form" method="POST" action=".">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn">
</form>
{% endblock %}

courses/templates/courses/members_course_list.html
{% extends 'base.html' %}

{% block content %}
<p><a href="{% url 'membership:overview' %}">< Back to membership overview</a></p>

<h2>Members courses</h2>
<p>Register for a club coaching course</p>

<div class="flex-sections">
    {% for course in object_list %}
    <section>
        <h3>{{ course }}</h3>
        {{ course.description|linebreaks }}
        <h4>Dates</h4>
        <ul>
            {% for session in course.sessions %}
            <li>{{ session.start_time }}</li>
            {% endfor %}
        </ul>
        <h4>Book</h4>
        <p>Course cost: £{{ course.members_price }}<br><small>The cost of the course will be added to the next membership invoice</small></p>
        <p><a href="{% url 'courses:members-course-booking' pk=course.id %}" class="btn">Book</a></p>
        {% if course.registered_members %}
            <p>Booked:</p>
            <ul>
                {% for booking in course.registered_members %}
                <li>
                    {{ booking.archer }}
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    </section>
    {% empty %}
    <section>There are no courses available for members to book right now.</section>
    {% endfor %}
</div>
{% endblock %}

courses/templates/courses/non_members_book_course.html
{% extends 'base.html' %}

{% block content %}
<p><a href="{% url 'courses:non-members-course-list' %}">< Back to course list</a></p>
<h2>{{ course }}</h2>
{{ course.description|linebreaks }}
<h4>Dates</h4>
<ul>
    {% for session in course.session_set.all %}
    <li>{{ session.start_time }}</li>
    {% endfor %}
</ul>
<p><strong>Fee:</strong> £{{ course.price }}</p>
<form class="form" method="POST" action=".">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn">
</form>
{% endblock %}

courses/templates/courses/non_members_course_list.html
{% extends 'base.html' %}

{% block content %}
<p><a href="{% url 'membership:overview' %}">< Back to overview</a></p>

<h2>Courses</h2>
<p>Register for a course</p>

<div class="flex-sections">
    {% for course in object_list %}
    <section>
        <h3>{{ course }}</h3>
        {{ course.description|linebreaks }}
        <h4>Dates</h4>
        <ul>
            {% for session in course.sessions %}
            <li>{{ session.start_time }}</li>
            {% endfor %}
        </ul>
        <p><strong>Fee:</strong> £{{ course.price }}</p>
        <p><a href="{% url 'courses:non-members-course-booking' pk=course.id %}" class="btn">Book</a></p>
        {% if course.registered_archers %}
            <p>Booked:</p>
            <ul>
                {% for booking in course.registered_archers %}
                <li>
                    {{ booking.archer }}
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    </section>
    {% empty %}
    <section>There are no courses available for non-members to book right now.</section>
    {% endfor %}
</div>
{% endblock %}