courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('holidays/', views.Holidays.as_view(), name='holidays'),
    path('holidays/book/', views.HolidaysBook.as_view(), name='holidays-book'),
    path('holidays/pay/', views.HolidaysPay.as_view(), name='holidays-payment'),
    path('dgs/', views.SchoolSignup.as_view(school='dgs'), name='dgs'),
    path('sbs/', views.SchoolSignup.as_view(school='sbs'), name='sbs'),
    path('maiden-erlegh/', views.SchoolSignup.as_view(school='maiden-erlegh'), name='maiden-erlegh'),
    # path('icknield/', views.SchoolSignup.as_view(school='icknield'), name='icknield'),
    # path('home-ed/', views.SchoolSignup.as_view(school='home-ed'), name='home-ed'),
    path('juniors/minis/', views.MinisInterestView.as_view(), name='minis-interest'),
    path('members/courses/', views.MembersCourseList.as_view(), name='members-course-list'),
    path('members/courses/external/', views.NonMembersCourseList.as_view(), name='non-members-course-list'),
    path('members/courses/<pk>/book/', views.MembersCourseBooking.as_view(), name='members-course-booking'),
    path(
        'members/courses/external/<pk>/book/',
        views.NonMembersCourseBooking.as_view(),
        name='non-members-course-booking',
    ),
    path('members/courses/pay/', views.NonMembersPayment.as_view(), name='non-members-payment'),
]

events/urls.py
from django.urls import path, register_converter

from . import api, views
from .converters import ApiDateConverter, SlotReferenceConverter

app_name = 'events'

register_converter(ApiDateConverter, 'date')
register_converter(SlotReferenceConverter, 'slot')

urlpatterns = [
    path('', views.EventList.as_view(), name='event-list'),
    path('<pk>/', views.BookEvent.as_view(), name='book-event'),
]

range_api_urlpatterns = [
    path('', api.date_list, name='date-list'),
    path('<date:date>/', api.date_slots, name='date-slots'),
    path('archers/', api.bookable_archers, name='bookable-archers'),
    path('group-booking-info/<slot:slot>/', api.group_booking_info, name='group-booking-info'),
    path('absentable-archers/<slot:slot>/', api.slot_absentable_archers, name='slot-absentable-archers'),
    path(
        'additional-bookable-archers/<slot:slot>/',
        api.slot_additional_bookable_archers,
        name='slot-additional-bookable-archers',
    ),
    # TODO: make book and cancel have slot details in the URL
    path('book/', api.book_slot, name='book-slot'),
    path('cancel/', api.cancel_slot, name='cancel-slot'),
    path('report-absence/<slot:slot>/', api.report_absence, name='report-absence'),
    path('book-in/<slot:slot>/', api.book_in, name='book-in'),
]

membership/urls.py
from django.urls import path, re_path

from . import views

app_name = 'membership'

urlpatterns = [
    path('', views.Overview.as_view(), name='overview'),
    re_path(r'^range/', views.RangeBooking.as_view(), name='range-booking'),
    path('attendance/<member_id>/', views.MemberAttendance.as_view(), name='member-attendance'),
    path('update/<member_id>/', views.MemberUpdate.as_view(), name='member-update'),
    path('payment/', views.PaymentDetails.as_view(), name='payment-details'),
]

venues/urls.py
from django.urls import path

from . import views

app_name = 'venues'


urlpatterns = [
    path('', views.VenueList.as_view(), name='index'),
    path('<slug:slug>/', views.VenueDetail.as_view(), name='detail'),
]

wallingford_castle/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordResetConfirmView, PasswordResetView,
)
from django.urls import include, path, reverse_lazy

from coaching.urls import coaching_api_urlpatterns
from events.urls import range_api_urlpatterns

from . import views
from .forms import ClientPasswordResetForm, RegisterForm

admin.autodiscover()


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('join/', views.Join.as_view(), name='join'),
    path('juniors/', views.Juniors.as_view(), name='juniors'),
    path('membership-interest/', views.MembershipInterestView.as_view(), name='membership-interest'),
    path('beginners/', include('beginners.urls', namespace='beginners')),
    path('coaching/', include('coaching.urls', namespace='coaching')),
    path('api/coaching/', include((coaching_api_urlpatterns, 'coaching-api'))),
    path('members/', include('membership.urls', namespace='membership')),
    path('members/events/', include('events.urls', namespace='events')),
    path('api/range/', include(range_api_urlpatterns)),
    path('tournaments/', include('tournaments.urls', namespace='tournaments')),
    path('events/', include('bookings.urls', namespace='bookings')),
    path('venues/', include('venues.urls', namespace='venues')),
    # TODO: Style header links
    path('accounts/login/', views.Login.as_view(), name='login'),
    path('accounts/password_reset/', PasswordResetView.as_view(
        form_class=ClientPasswordResetForm,
    ), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        form_class=RegisterForm,
        template_name='registration/register.html',
        success_url=reverse_lazy('membership:overview'),
    ), name='register'),
    path('admin/', admin.site.urls),
    path('webhooks/stripe/', include('payments.urls', namespace='payments')),
    path('', include('courses.urls', namespace='courses')),
]

venues/models.py
from django.db import models
from django.urls import reverse

INDOOR_OUTDOOR = (
    ('indoor', 'Indoor'),
    ('outdoor', 'Outdoor'),
)


class Venue(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.TextField()
    google_maps_link = models.URLField()
    season = models.CharField(max_length=20, choices=INDOOR_OUTDOOR)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('venues:detail', kwargs={'slug': self.slug})

membership/views.py
import json

from django.conf import settings
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, TemplateView, UpdateView, View

import requests
import stripe
from braces.views import MessageMixin

from beginners.models import STATUS_FAST_TRACK, STATUS_ON_COURSE
from coaching.forms import TrialContinueForm
from coaching.models import ArcherSeason, Trial
from courses.models import Attendee, Course
from membership.models import Member
from records.models import Achievement
from wallingford_castle.mixins import FullMemberRequired
from wallingford_castle.models import Season

from .forms import SeniorMemberForm, JuniorMemberForm


class Overview(FullMemberRequired, TemplateView):
    template_name = 'membership/overview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['members'] = Member.objects.managed_by(self.request.user).select_related('archer')
        context['monthly_fee'] = sum(
            member.plan_cost for member in context['members'] if member.archer.user == self.request.user
        )
        context['beginners'] = self.request.user.beginner_set.all()
        context['beginners_to_pay'] = sum(
            beginner.fee for beginner in self.request.user.beginner_set.filter(
                paid=False,
                status__in=[STATUS_ON_COURSE, STATUS_FAST_TRACK],
            )
        )
        context['trials'] = Trial.objects.filter_ongoing().filter(
            archer__user=self.request.user,
        ).select_related('archer', 'group')
        context['trials_to_pay'] = sum(
            trial.fee for trial in context['trials'] if not trial.paid
        )
        context['completed_trials'] = Trial.objects.filter_completed().filter(
            archer__user=self.request.user,
        ).select_related('archer', 'group')
        for trial in context['completed_trials']:
            trial.form = TrialContinueForm(trial=trial)
        context['course_attendees'] = Attendee.objects.filter(
            archer__user=self.request.user,
            course__can_book_individual_sessions=False,
            member=False,
        ).order_by('course').select_related('archer', 'course')
        context['course_fees_to_pay'] = sum(
            attendee.fee for attendee in context['course_attendees'] if not attendee.paid
        )
        if not context['members']:
            context['bookable_courses'] = Course.objects.filter(
                open_for_bookings=True,
                open_to_non_members=True,
            )
        context['STRIPE_KEY'] = settings.STRIPE_KEY

        achievements = Achievement.objects.filter(
            archer__in=[member.archer for member in context['members']],
        ).order_by('-date_awarded')
        for achievement in achievements:
            for member in context['members']:
                if member.archer_id == achievement.archer_id:
                    if not hasattr(member, 'achievements'):
                        member.achievements = []
                    member.achievements.append(achievement)

        current_season = Season.objects.get_current()
        next_season = Season.objects.get_next(current_season)
        seasons = list(filter(None, [current_season, next_season]))
        plans = ArcherSeason.objects.filter(
            season__in=[season.pk for season in seasons],
            archer__in=[member.archer for member in context['members']],
        ).order_by('season__start_date')
        for plan in plans:
            for member in context['members']:
                if member.archer_id == plan.archer_id:
                    if plan.season_id == current_season.pk:
                        member.current_season_plan = plan
                    if plan.season_id == next_season.pk:
                        member.next_season_plan = plan

        return context


class MemberAttendance(FullMemberRequired, DetailView):
    model = Member
    template_name = 'membership/attendance.html'
    pk_url_kwarg = 'member_id'

    def get_queryset(self):
        return Member.objects.managed_by(self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['archer'] = self.object.archer
        context['attendance_record'] = self.object.archer.event_attendance_set.order_by(
            '-event__date'
        ).select_related('event')
        return context


class MemberUpdate(FullMemberRequired, MessageMixin, UpdateView):
    template_name = 'membership/member-update.html'
    pk_url_kwarg = 'member_id'
    success_url = reverse_lazy('membership:overview')

    def get_form_class(self):
        if self.object.archer.age == 'junior':
            return JuniorMemberForm
        return SeniorMemberForm

    def get_queryset(self):
        return Member.objects.managed_by(self.request.user).select_related('archer')

    def get_object(self):
        obj = super().get_object()
        self.original_plan = obj.plan
        return obj

    def form_valid(self, form):
        response = super().form_valid(form)
        self.messages.success('Details successfully updated!')
        if settings.SLACK_MEMBERSHIP_HREF:
            data = json.dumps({
                'icon_emoji': ':exclamation:',
                'text': '%s has updated details!\n%s' % (
                    self.object.archer.name,
                    self.request.build_absolute_uri(
                        reverse(
                            'admin:membership_member_change',
                            args=(self.object.pk,),
                        )
                    ),
                )
            })
            try:
                requests.post(settings.SLACK_MEMBERSHIP_HREF, data=data)
            except Exception:
                pass
        return response


class PaymentDetails(MessageMixin, View):
    def get(self, request, *args, **kwargs):
        user = self.request.user
        membership_overview_url = reverse('membership:overview')
        customer_id = user.customer_id or None
        subscription_id = user.subscription_id or None
        if not subscription_id or not customer_id:
            session = stripe.checkout.Session.create(
                line_items=[
                    {'price': price, 'quantity': quantity}
                    for price, quantity in user.get_membership_prices().items()
                ],
                customer=customer_id,
                customer_creation=None if customer_id else 'always',
                mode='subscription',
                payment_method_types=['card'],
                success_url=self.request.build_absolute_uri(membership_overview_url),
                cancel_url=self.request.build_absolute_uri(membership_overview_url),
            )
            return redirect(session.url, status_code=303)
        else:
            session = stripe.checkout.Session.create(
                mode='setup',
                customer=customer_id,
                payment_method_types=['card'],
                success_url=self.request.build_absolute_uri(membership_overview_url),
                cancel_url=self.request.build_absolute_uri(membership_overview_url),
            )
            return redirect(session.url, status_code=303)


class RangeBooking(FullMemberRequired, TemplateView):
    template_name = 'membership/range_booking.html'

venues/views.py
from django.views.generic import DetailView, ListView

from .models import Venue


class VenueList(ListView):
    template_name = 'venues/venue_list.html'
    model = Venue

    def get_queryset(self):
        return Venue.objects.filter(active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        indoor = []
        outdoor = []
        for venue in self.object_list:
            if venue.season == 'indoor':
                indoor.append(venue)
            else:
                outdoor.append(venue)
        context.update(indoor=indoor, outdoor=outdoor)
        return context


class VenueDetail(DetailView):
    template_name = 'venues/venue_detail.html'
    model = Venue

    def get_queryset(self):
        return Venue.objects.filter(active=True)

wallingford_castle/views.py
import json

from django.conf import settings
from django.contrib.auth.views import LoginView
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, TemplateView

import requests
from braces.views import MessageMixin

from courses.forms import CourseInterestForm

from .forms import MembershipInterestForm


class HomeView(MessageMixin, TemplateView):
    template_name = 'home.html'


class Join(TemplateView):
    template_name = 'join.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['membership_form'] = MembershipInterestForm()
        return context


class Juniors(TemplateView):
    template_name = 'juniors.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['minis_form'] = CourseInterestForm(course_type='minis')
        return context


class MembershipInterestView(MessageMixin, CreateView):
    form_class = MembershipInterestForm
    template_name = 'membership_form.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        response = super().form_valid(form)
        self.messages.success('Thanks for your interest! We will be in touch soon.')
        if settings.SLACK_MEMBERSHIP_HREF:
            data = json.dumps({
                'icon_emoji': ':wave:',
                'text': 'New membership interest received for %s!\n%s' % (
                    form.cleaned_data['name'],
                    self.request.build_absolute_uri(
                        reverse(
                            'admin:wallingford_castle_membershipinterest_change',
                            args=(form.instance.pk,),
                        )
                    ),
                )
            })
            try:
                requests.post(settings.SLACK_MEMBERSHIP_HREF, data=data)
            except Exception:
                pass
        return response


class Login(LoginView):
    def get_redirect_url(self):
        user = self.request.user
        if user.is_authenticated and user.tournament_only:
            return reverse('tournaments:home')
        return reverse('membership:overview')

wallingford_castle/templates/base.html
{% load render_bundle from webpack_loader %}

<!doctype html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% if headline %}{{ headline }} | {% endif %}{% endblock %}Wallingford Castle Archers</title>
        <link href='//fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{{ STATIC_URL }}css/base.css?{{ SOURCE_VERSION }}" />
        <link rel="apple-touch-icon" sizes="180x180" href="{{ STATIC_URL }}favicon/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ STATIC_URL }}favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ STATIC_URL }}favicon/favicon-16x16.png">
        <link rel="manifest" href="{{ STATIC_URL }}favicon/site.webmanifest">
        <link rel="mask-icon" href="{{ STATIC_URL }}favicon/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="shortcut icon" href="{{ STATIC_URL }}favicon/favicon.ico">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="msapplication-config" content="{{ STATIC_URL }}favicon/browserconfig.xml">
        <meta name="theme-color" content="#ffffff">
        {% render_bundle 'global' 'css' %}
        {% block meta %}
        <meta property="og:image" content="https://wallingfordcastle.co.uk{{ STATIC_URL }}img/{% block og_image %}scas{% endblock %}.jpg" />
        {% endblock %}
    </head>
    <body>
        <header>
            <div class="container">
                <h1><a href="{% url 'home' %}">Wallingford Castle Archers</a></h1>
                <div class="user-actions">
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}">Sign out</a>
                    {% else %}
                    <a href="{% url 'login' %}">Sign in</a>
                    {% endif %}
                </div>
            </div>
        </header>
        <div class="container">
            <nav class="nav">
                <a class="nav__link" href="{% url 'home' %}">Home</a>
                {% if user.is_authenticated and not user.tournament_only %}
                    <a class="nav__link" href="{% url 'membership:overview' %}">Members</a>
                {% endif %}
                <a class="nav__link" href="{% url 'courses:holidays' %}">Holiday Archery</a>
                <a class="nav__link" href="{% url 'beginners:index' %}">Learn archery</a>
                <a class="nav__link" href="{% url 'juniors' %}">Juniors & minis</a>
                <a class="nav__link" href="{% url 'join' %}">Join the club</a>
                <a class="nav__link" href="{% url 'bookings:index' %}">Events</a>
                <a class="nav__link" href="{% url 'tournaments:home' %}">Tournaments</a>
                <a class="nav__link" href="{% url 'venues:index' %}">Venues</a>
            </nav>
        </div>
        {% block hero %}
        {% endblock %}
        {% if messages %}
        <section class="messages">
            <div class="container">
                {% for message in messages %}
                <p class="message {{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </div>
        </section>
        {% endif %}
        <article>
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </article>
        <footer>
            <div class="container">
                <div class="footer">
                    <div class="footer__col">
                        <img src="{{ STATIC_URL }}img/on-target.png" class="footer__on-target" />
                        <div class="footer__specialisms">
                            <img src="{{ STATIC_URL }}img/on-target-community.png" class="footer__specialism" />
                            <img src="{{ STATIC_URL }}img/on-target-young.png" class="footer__specialism" />
                            <img src="{{ STATIC_URL }}img/on-target-performance.png" class="footer__specialism" />
                        </div>
                    </div>
                    <div class="footer__col footer__col--links">
                        <a href="mailto:hello@wallingfordcastle.co.uk">Contact us</a>
                        <a href="{{ STATIC_URL }}docs/articles.pdf">Articles of Association</a>
                        <a href="{{ STATIC_URL }}docs/admin_procs.pdf?v=2022">Club Administrative Procedures</a>
                        <a href="{{ STATIC_URL }}docs/code_of_conduct.pdf">Code of conduct - Members</a>
                        <a href="{{ STATIC_URL }}docs/parents_conduct.pdf">Code of conduct - Parents</a>
                        <span>Wallingford Castle Archers Limited is<br>a Company Limited by Guarantee<br>registered in England and Wales</span>
                    </div>
                </div>
            </div>
        </footer>
        <div id="modal-container"></div>
        {% if GA_TRACKING %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', '{{ GA_TRACKING }}', 'auto');
            ga('send', 'pageview');
        </script>
        {% endif %}
        {% render_bundle 'global' 'js' %}
    </body>
</html>

wallingford_castle/templates/home.html
{% extends 'base.html' %}

{% block hero %}
<div class="hero hero--scas">
    <h1>Wallingford Castle Archers</h1>
</div>
{% endblock %}

{% block content %}
<div class="flex-sections">
    <section>
        <h2>About</h2>
        <p>
        Wallingford Castle Archers is one of the largest archery clubs in the
        UK, with over 200 members. We have a family friendly atmosphere with
        around half our members under 18, but we are also competitive and have
        had success at national level. Archery is a highly inclusive sport, with juniors
        able to learn along side grandparents, and able bodied alongside disabled.
        </p>
        <p>
        We have shooting at least 5 days a week, and a wide range of coach led
        training groups to suit all ages and abilities. We shoot at a range of
        venues across South Oxfordshire, based around our main hubs at
        Wallingford Sports Park and Wallingford School.
        </p>
    </section>
    <section>
        <h2>Get into archery</h2>
        <p>
        Beginners courses are the ideal introduction to the sport for adults.
        You'll learn all the basics including how to set up, shoot the bow and
        score your arrows.
        </p>
        <p>
        <a class="btn" href="{% url 'beginners:index' %}">Find out more</a>
        </p>
        <p>
        For children wanting to get started, we run Minis sessions for children
        born in 2013 or later, and Arrows sessions for children born in
        2007-2010. These are weekly structured sessions with plenty
        opportunities to earn their beginners badges.
        </p>
        <p>
        Children are welcome to start a 4 week trial at any time.
        </p>
        <p>
        <a class="btn" href="{% url 'juniors' %}">Find out more</a>
        </p>
    </section>
    <section>
        <h2>Compete</h2>
        <p>We host regular competitions at Wallingford Castle Archers.</p>
        <p>
        All our summer competitions are now open to enter! You can find details
        of our events are on the Tournaments page.
        </p>
        <p>
        <a class="btn" href="{% url 'tournaments:home' %}">Find out more</a>
        </p>
   </section>
</div>
{% endblock %}

wallingford_castle/templates/join.html
{% extends 'base.html' %}

{% block og_image %}join{% endblock %}

{% block hero %}
<div class="hero hero--join">
    <h1>Join the club</h1>
</div>
{% endblock %}

{% block content %}
<div class="flex-sections">
    <section>
        <h2>Join the club</h2>
        <p>
        Wallingford Castle Archers is an active club with over 200 members.
        We cater for all archers - whether you are 6 or 106, a complete
        beginner or an olympic athlete.
        </p>
        <p>
        We shoot all through the year with some shooting taking place at least
        5 days a week.
        </p>
        <h3>Coaching</h3>
        <p>
        We run a wide range of group coaching programs for archers of all ages
        and levels. We run groups for novices, intermediates and performance
        adults, as well as several levels of junior groups, and minis sessions.
        For most groups we run sessions on at least two different days in the
        week to maximise availability for everyone, although archers typically
        only attend one.
        </p>
        <p>
        Adult coaching groups are £30/month and junior coaching groups are
        £25/month, both paid monthly with membership. We also have more
        advanced junior groups which meet more regularly for those who wish to
        take competitive archery seriously. Minis sessions are £5/week and are
        booked in blocks by term.
        </p>
    </section>
    <section>
        <h2>Archery GB Membership</h2>
        <p>
            All club members must be members of Archery GB. You are responsible
            for keeping your own membership up to date, and it is required for
            insurance purposes.
        </p>
        <p>
            Membership of Archery GB is not sufficient to guarantee acceptance
            as a club member. New archers should complete a
            <a href="{% url 'beginners:index' %}">beginners course</a> first,
            returning archers should contact the
            <a href="mailto:hello@wallingfordcastle.co.uk">club coaches</a> to
            arrange an assessment.
        </p>
        <p>
            <a class="btn" href="https://agb.sport80.com/public/wizard/a/183/home">Join Archery GB</a>
        </p>
        <h2>Membership types</h2>
        <p>
            <strong>Adult members</strong><br>
            £20 per calendar month. Membership includes open practice sessions
            and use of club equipment.
        </p>
        <p>
            <strong>Concession members</strong><br>
            £17 calendar month. Concession membership is available to all
            archers aged 6-20, and any archers with a disability. Membership
            includes open sessions, use of club equipment.
        </p>
        <p>
           Archers aged 6-11 (attending primary school) will be part of the
           minis club on Sundays or Mondays which has no standing monthly
           charge, but weekly session charges.
        </p>
    </section>
    <section>
        <h2>Register interest</h2>
        <form class="form page-form" method="POST" action="{% url 'membership-interest' %}">
            {% csrf_token %}
            {{ membership_form }}
            <input type="submit" class="btn">
        </form>
    </section>
</div>
{% endblock %}

wallingford_castle/templates/membership_form.html
{% extends 'base.html' %}

{% block content %}
<form class="form" method="POST" action=".">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn">
</form>
{% endblock %}

wallingford_castle/templates/venues.html
{% extends 'base.html' %}

{% block og_image %}wsp-rainbow{% endblock %}

{% block hero %}
<div class="hero hero--wsp-rainbow">
    <h1>Venues</h1>
</div>
{% endblock %}

{% block content %}
<div class="flex-sections">
    <section>
        <h2>Indoor shooting</h2>
        <p>
        Indoor sessions run from October to March. We have a number of indoor
        shooting venues in the Wallingford area, at this point which we will be
        able to use in Winter 2021-22 is unclear.
        </p>
        <p>
        We aim to offer open shooting at least 3 times per week, in addition to
        a wide range of training groups.
        </p>
        <!-- iframe
            width="100%"
            height="300"
            frameborder="0" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDGuvasiOAUbxa4w_xoZ8YaY38M9Vpz2Ec&q=Wallingford%20Castle%20Archers%20Indoors,%20Wallingford&zoom=14" allowfullscreen>
        </iframe -->
        <!--iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2347.5762112006582!2d-1.177989222469583!3d51.61400792007151!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNTHCsDM2JzUxLjUiTiAxwrAxMCczNy4wIlc!5e0!3m2!1sen!2suk!4v1603706438512!5m2!1sen!2suk" width="100%" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe-->
   </section>
    <section>
        <h2>Outdoor shooting</h2>
        <p>
        Outdoor sessions run from April to September. Club sessions typically
        run on Wednesday, Friday and Sunday, but the range is open most days of
        the week to more experienced members.
        </p>
        <p>
        Our outdoor range is based at Wallingford Sports Park, on the northern fields.
        We shoot outdoors from from April to September. Archery is an all
        weather sport, and sessions continue in most weather conditions.
        </p>
        <iframe
            width="100%"
            height="300"
            frameborder="0" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDGuvasiOAUbxa4w_xoZ8YaY38M9Vpz2Ec&q=Wallingford%20SportsPark,%20Wallingford&zoom=14" allowfullscreen>
        </iframe>
    </section>
    <section>
        <h2>Under 18s</h2>
        <p>
        Wallingford Castle Archers aim to make archery as accessible as
        possible for young people. However, we also have to ensure that we
        follow safeguarding guidance and help to keep every child safe.
        </p>
        <p>
        Those children of primary school age (up to 11) are classified as
        "minis", with older children under the age of 18 classified as
        "juniors".
        </p>
        <p>
        Minis members may only attend minis sessions. Parents do not need to
        stay for minis sessions. However, those in year 5 or 6 who have
        attained their white arrow award may be invited to attend other
        sessions. For the junior session, parents may leave the child with us.
        For other sessions, they must stay.
        </p>
        <p>
        Junior members may attend open sessions with parental supervision. When
        they have achieved their blue arrow award and have their own equipment
        (moved up to Junior Team level) they may shoot without supervision at
        most sessions, subject to availability and communication with coaches.
        </p>
    </section>
</div>
{% endblock %}