coaching/urls.py
from django.urls import path

from . import api, views

app_name = 'coaching'

urlpatterns = [
    path('', views.GroupsOverview.as_view(), name='overview'),
    path('pay/', views.TrialPayment.as_view(), name='trial-payment'),
    path('trial/continue/<int:trial_pk>/', views.TrialContinue.as_view(), name='trial-continue'),
    path('<int:pk>-<slug:group>/', views.GroupReport.as_view(), name='group-report'),
    path('upcoming/<int:pk>-<slug:group>/', views.UpcomingGroupReport.as_view(), name='upcoming-group-report'),
    path('<int:pk>-<slug:group>/sessions/', views.GroupSchedule.as_view(), name='group-schedule'),
    path(
        'upcoming/<int:pk>-<slug:group>/sessions/',
        views.UpcomingGroupSchedule.as_view(),
        name='upcoming-group-schedule',
    ),

    path('<int:archer_id>/event-plan/', views.EventPlan.as_view(), name='event-plan'),
    path('<int:archer_id>/upcoming/event-plan/', views.NextEventPlan.as_view(), name='next-event-plan'),
]

coaching_api_urlpatterns = [
    path('plan/<int:plan_id>/', api.plan_info, name='plan-info'),
    path('plan/register/<int:plan_id>/<int:event_id>/', api.register, name='register'),
]

events/urls.py
from django.urls import path, register_converter

from . import api, views
from .converters import ApiDateConverter, SlotReferenceConverter

app_name = 'events'

register_converter(ApiDateConverter, 'date')
register_converter(SlotReferenceConverter, 'slot')

urlpatterns = [
    path('', views.EventList.as_view(), name='event-list'),
    path('<pk>/', views.BookEvent.as_view(), name='book-event'),
]

range_api_urlpatterns = [
    path('', api.date_list, name='date-list'),
    path('<date:date>/', api.date_slots, name='date-slots'),
    path('archers/', api.bookable_archers, name='bookable-archers'),
    path('group-booking-info/<slot:slot>/', api.group_booking_info, name='group-booking-info'),
    path('absentable-archers/<slot:slot>/', api.slot_absentable_archers, name='slot-absentable-archers'),
    path(
        'additional-bookable-archers/<slot:slot>/',
        api.slot_additional_bookable_archers,
        name='slot-additional-bookable-archers',
    ),
    # TODO: make book and cancel have slot details in the URL
    path('book/', api.book_slot, name='book-slot'),
    path('cancel/', api.cancel_slot, name='cancel-slot'),
    path('report-absence/<slot:slot>/', api.report_absence, name='report-absence'),
    path('book-in/<slot:slot>/', api.book_in, name='book-in'),
]

wallingford_castle/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordResetConfirmView, PasswordResetView,
)
from django.urls import include, path, reverse_lazy

from coaching.urls import coaching_api_urlpatterns
from events.urls import range_api_urlpatterns

from . import views
from .forms import ClientPasswordResetForm, RegisterForm

admin.autodiscover()


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('join/', views.Join.as_view(), name='join'),
    path('juniors/', views.Juniors.as_view(), name='juniors'),
    path('membership-interest/', views.MembershipInterestView.as_view(), name='membership-interest'),
    path('beginners/', include('beginners.urls', namespace='beginners')),
    path('coaching/', include('coaching.urls', namespace='coaching')),
    path('api/coaching/', include((coaching_api_urlpatterns, 'coaching-api'))),
    path('members/', include('membership.urls', namespace='membership')),
    path('members/events/', include('events.urls', namespace='events')),
    path('api/range/', include(range_api_urlpatterns)),
    path('tournaments/', include('tournaments.urls', namespace='tournaments')),
    path('events/', include('bookings.urls', namespace='bookings')),
    path('venues/', include('venues.urls', namespace='venues')),
    # TODO: Style header links
    path('accounts/login/', views.Login.as_view(), name='login'),
    path('accounts/password_reset/', PasswordResetView.as_view(
        form_class=ClientPasswordResetForm,
    ), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        form_class=RegisterForm,
        template_name='registration/register.html',
        success_url=reverse_lazy('membership:overview'),
    ), name='register'),
    path('admin/', admin.site.urls),
    path('webhooks/stripe/', include('payments.urls', namespace='payments')),
    path('', include('courses.urls', namespace='courses')),
]

coaching/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from records.classifications import CLASSIFICATION_CHOICES
from wallingford_castle.models import AGE_CHOICES

DAY_CHOICES = (
    (0, 'Monday'),
    (1, 'Tuesday'),
    (2, 'Wednesday'),
    (3, 'Thursday'),
    (4, 'Friday'),
    (5, 'Saturday'),
    (6, 'Sunday'),
)


class TrainingGroupType(models.Model):
    name = models.CharField(max_length=255)
    age_group = models.CharField(max_length=20, choices=AGE_CHOICES)
    trial_fee = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name


class TrainingGroup(models.Model):
    level = models.ManyToManyField(TrainingGroupType)
    season = models.ForeignKey('wallingford_castle.Season', on_delete=models.PROTECT)
    coaches = models.ManyToManyField('wallingford_castle.Archer', related_name='coached_groups')
    participants = models.ManyToManyField('wallingford_castle.Archer', related_name='training_groups', blank=True)
    max_participants = models.PositiveIntegerField(blank=True, null=True)
    session_day = models.SmallIntegerField(choices=DAY_CHOICES)
    session_start_time = models.TimeField()
    session_duration = models.DurationField(default=datetime.timedelta(minutes=90))
    number_of_targets = models.PositiveIntegerField(blank=True, null=True)
    target = models.PositiveIntegerField(default=1)
    b_range = models.BooleanField(default=False)
    venue = models.ForeignKey('venues.Venue', on_delete=models.PROTECT)

    @property
    def group_name(self):
        return '/'.join(map(str, self.level.all()))

    @property
    def slug(self):
        return '%s-%s' % (
            self.get_session_day_display().lower(),
            '-'.join(map(lambda s: str(s).replace(' ', '_').lower(), self.level.all())),
        )

    @property
    def time(self):
        return '%ss at %s' % (self.get_session_day_display(), self.session_start_time.strftime('%H:%M'))

    @property
    def session_end_time(self):
        today = timezone.now().date()
        possible_start = datetime.datetime.combine(today, self.session_start_time)
        possible_end = possible_start + self.session_duration
        return possible_end.time()

    @property
    def session_minutes(self):
        return int(self.session_duration.seconds / 60)

    def possible_dates(self, after=None):
        first_date = after or self.season.start_date
        while first_date.weekday() != self.session_day:
            first_date += datetime.timedelta(days=1)
        dates = [first_date]
        while dates[-1] <= self.season.end_date - datetime.timedelta(days=7):
            dates.append(dates[-1] + datetime.timedelta(days=7))
        return dates

    def next_session(self):
        today = timezone.now().date()
        return self.groupsession_set.filter_running().filter(
            start__date__gte=today,
        ).first()

    def additional_bookable_archers(self, user, already_booked=None):
        user_archers = set(m.archer for m in user.managed_members)
        current_archers = set(self.participants.all())
        if already_booked is not None:
            current_archers = current_archers & set(already_booked)

        levels = self.level.all()
        other_groups = TrainingGroup.objects.filter(level__in=levels, season_id=self.season_id)
        candidate_archers = set()
        for group in other_groups:
            candidate_archers |= set(group.participants.all())

        if already_booked is not None:
            candidate_archers -= set(already_booked)

        return sorted(user_archers & candidate_archers - current_archers, key=lambda a: a.name)

    def __str__(self):
        return '%s %s group (%s)' % (self.get_session_day_display(), self.group_name, self.season)


class GroupSessionQuerySet(models.QuerySet):
    def filter_running(self):
        return self.filter(cancelled_because='')


class GroupSession(models.Model):
    group = models.ForeignKey(TrainingGroup, on_delete=models.CASCADE)
    start = models.DateTimeField()
    cancelled_because = models.TextField(blank=True, default='')
    booked_slot = models.OneToOneField('events.BookedSlot', blank=True, null=True, on_delete=models.SET_NULL)

    objects = models.Manager.from_queryset(GroupSessionQuerySet)()

    class Meta:
        unique_together = ['group', 'start']

    def __str__(self):
        return '%s session on %s' % (self.group, self.start)


class Absence(models.Model):
    session = models.ForeignKey(GroupSession, on_delete=models.CASCADE)
    archer = models.ForeignKey('wallingford_castle.Archer', on_delete=models.CASCADE)
    reason = models.TextField(blank=True, default='')

    class Meta:
        unique_together = ('session', 'archer')

    def __str__(self):
        return '%s absent from %s' % (self.archer, self.session)


class TrialQuerySet(models.QuerySet):
    def filter_ongoing(self):
        return self.filter(session_4__gte=timezone.now().date())

    def filter_completed(self):
        return self.filter(
            session_4__lt=timezone.now() + datetime.timedelta(days=5),
            archer__member__isnull=True,
        )


class Trial(models.Model):
    archer = models.ForeignKey('wallingford_castle.Archer', on_delete=models.CASCADE)
    group = models.ForeignKey(TrainingGroup, on_delete=models.CASCADE)
    session_1 = models.DateTimeField()
    session_2 = models.DateTimeField()
    session_3 = models.DateTimeField()
    session_4 = models.DateTimeField()
    paid = models.BooleanField(default=False)

    objects = models.Manager.from_queryset(TrialQuerySet)()

    def __str__(self):
        return '%s trial at %s' % (self.archer, self.group)

    @property
    def fee(self):
        return self.group.level.filter(trial_fee__gt=0).order_by('-trial_fee').first().trial_fee or 0


class CompetitiveTrack(models.Model):
    season = models.ForeignKey('wallingford_castle.Season', on_delete=models.PROTECT)
    number = models.IntegerField()
    name = models.CharField(max_length=100)

    class Meta:
        unique_together = ['season', 'number']

    @property
    def slug(self):
        return 'track-%s-%s' % (self.number, slugify(self.season.name))

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=255)
    event_format = models.CharField(max_length=100)
    track = models.ForeignKey(CompetitiveTrack, on_delete=models.CASCADE)
    date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    venue = models.CharField(max_length=255)
    venue_post_code = models.CharField(max_length=20)
    age_groups = models.CharField(max_length=100)
    scayt = models.BooleanField(default=False)
    tournament = models.ForeignKey('tournaments.Tournament', on_delete=models.SET_NULL, blank=True, null=True)
    event = models.ForeignKey('events.Event', on_delete=models.SET_NULL, blank=True, null=True)
    club_trip = models.BooleanField(default=False)
    entry_link = models.URLField(blank=True, null=True)

    class Meta:
        unique_together = ['date', 'name']

    def __str__(self):
        return self.name


class ArcherSeason(models.Model):
    archer = models.ForeignKey('wallingford_castle.Archer', on_delete=models.CASCADE)
    season = models.ForeignKey('wallingford_castle.Season', on_delete=models.PROTECT)
    target_classification = models.CharField(max_length=3, choices=CLASSIFICATION_CHOICES)
    personalised_target_comments = models.TextField(blank=True, default='')
    tracks = models.ManyToManyField(CompetitiveTrack, through='ArcherTrack')
    events = models.ManyToManyField(Event, through='Registration')

    class Meta:
        unique_together = ['archer', 'season']

    def __str__(self):
        return '%s in the %s season' % (self.archer, self.season)

    def get_absolute_url(self):
        if self.season.is_current:
            return reverse('coaching:event-plan', kwargs={'archer_id': self.archer_id})
        return reverse('coaching:next-event-plan', kwargs={'archer_id': self.archer_id})


class ArcherTrack(models.Model):
    track = models.ForeignKey(CompetitiveTrack, on_delete=models.CASCADE)
    archer_season = models.ForeignKey(ArcherSeason, on_delete=models.CASCADE)
    recommended_events_comments = models.TextField(blank=True, default='')

    class Meta:
        unique_together = ['track', 'archer_season']

    def __str__(self):
        return '%s - %s track' % (self.archer_season, self.track)


class Registration(models.Model):
    STATUS_CHOICES = (
        ('definite', 'Yes, I am definitely attending'),
        ('booked', 'Yes, I am booked in'),
        ('maybe', 'I might be attending'),
        ('no', 'I will not be attending'),
    )
    TRANSPORT_CHOICES = (
        ('required', 'I can only attend if transport is offered'),
        ('interested', 'Transport for archer would be helpful but we could make our own way there'),
        ('plus-parent', 'Transport for archer and a parent would be helpful but we could make our own way there'),
        ('own-way', 'We will make our own way there'),
    )

    archer_season = models.ForeignKey(ArcherSeason, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.SET_NULL, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    wants_transport = models.CharField(max_length=20, choices=TRANSPORT_CHOICES, blank=True, null=True)

    class Meta:
        unique_together = ['event', 'archer_season']

    def __str__(self):
        return '%s registered for %s' % (self.archer_season.archer, self.event)

coaching/forms.py
from django import forms


class TrialContinueForm(forms.Form):
    name = forms.CharField(max_length=200)
    date_of_birth = forms.DateField()
    agb_number = forms.CharField(help_text='Archery GB membership is a requirement of club membership')
    contact_number = forms.CharField(
        max_length=20,
        help_text='Number for a parent or guardian to be used in case of emergency.',
    )
    address = forms.CharField(
        widget=forms.Textarea,
    )

    def __init__(self, trial, **kwargs):
        self.trial = trial
        initial = {
            'name': trial.archer.name,
            'date_of_birth': trial.archer.date_of_birth,
            'contact_number': trial.archer.contact_number,
        }
        initial.update(kwargs.get('initial', {}))
        kwargs['initial'] = initial
        super().__init__(**kwargs)

    def save(self):
        archer = self.trial.archer
        archer.agb_number = self.cleaned_data['agb_number']
        archer.name = self.cleaned_data['name']
        archer.date_of_birth = self.cleaned_data['date_of_birth']
        archer.contact_number = self.cleaned_data['contact_number']
        archer.address = self.cleaned_data['address']
        archer.save()

        group_level = self.trial.group.level.first().name
        member = archer.member_set.create(
            membership_type='minis' if group_level.startswith('Mini') else 'full',
            coaching_subscription=group_level in ['Junior Arrows', 'Novice'],
        )
        self.trial.group.participants.add(archer)
        return member

coaching/templates/coaching/event_plan.html
{% extends 'base.html' %}

{% block content %}
<p><a href="{% url 'membership:overview' %}">< Back to membership overview</a></p>
<h2>Event plan - {{ plan }}</h2>
<div id="app-event-plan" data-plan="{{ plan.pk }}"></div>
{% endblock %}

coaching/templates/coaching/group_report.html
{% extends 'base.html' %}

{% block title %}{{ group }} - {{ season }}{% endblock %}

{% block content %}
<a href="{% url 'coaching:overview' %}">< Back to list of groups</a>
<h2>{{ group }}</h2>
<p><a href="{% url schedule_url_name pk=group.pk group=group.slug %}">View upcoming session times ></a></p>
<h3>Archers</h3>
<table class="table">
    <thead>
        <th>Name</th>
        <th>Age</th>
        <th>AGB number</th>
        <th>Badges</th>
    <thead>
    {% for archer in archers %}
    <tr>
        <td data-email="{{ archer.user.email }}">{{ archer }}</td>
        <td>{{ archer.age_group }}<br><small>{{ archer.date_of_birth }}</small></td>
        <td>{% if archer.agb_number %}{{ archer.agb_number }}{% else %}Pending{% endif %}</td>
        <td>
            Outdoor: {{ archer.best_outdoor.name|default:"None" }}<br>
            Portsmouth: {{ archer.best_portsmouth.name|default:"None" }}<br>
            WA18: {{ archer.best_wa_18.name|default:"None" }}<br>
            Beginner: {{ archer.best_beginner.name|default:"None" }}
        </td>
    </tr>
    {% endfor %}
    {% for trial in current_trials %}
    <tr>
        <td data-email="{{ trial.archer.user.email }}">
            {{ trial.archer }}
        </td>
        <td>{{ trial.archer.date_of_birth }}</td>
        <td>Trial ends {{ trial.session_4.date }}</td>
    </tr>
    {% endfor %}
</table>

<h3>Group details</h3>
<p>Meets on {{ group.time }}</p>
<p>Coached by:
    {% for coach in group.coaches.all %}
        {{ coach }}
    {% endfor %}
</p>
{% if user.is_superuser %}
<a id="email" href="#">Copy group emails</a>
<script type="text/javascript">
    document.getElementById('email').addEventListener('click', function(ev) {
        ev.preventDefault();
        var emails = [];
        document.body.querySelectorAll(('[data-email]')).forEach(function(el) {
            emails.push(el.dataset.email);
        });
        navigator.clipboard.writeText(emails.join(' ')).then(function() {
            ev.target.innerHTML = 'Done!';
        });
    });
</script>
{% endif %}

{% endblock %}

coaching/templates/coaching/group_schedule.html
{% extends 'base.html' %}

{% block title %}{{ group }} - {{ season }}{% endblock %}

{% block content %}

<p>
    {% if is_coach %}
    <a href="{% url 'coaching:group-report' pk=group.pk group=group.slug %}">< Back to group</a>
    {% else %}
    <a href="{% url 'membership:overview' %}">< Back to membership overview</a>
    {% endif %}
</p>

<h2>{{ group }} schedule</h2>
<p>Upcoming sessions, up to {{ season.end_date }}. Session venues and timings may change each season.</p>
<p>Sessions take place at {{ group.venue }}, between {{ group.session_start_time }} and {{ group.session_end_time }} on {{ group.get_session_day_display }}s.</p>

<ul>
{% for session in sessions %}
<li>
    {% if session.cancelled_because %}<em>{% endif %}
    {{ session.start.date }}
    <small>{% if session.cancelled_because %} Not running due to {{ session.cancelled_because }}.{% endif %}</small>
    {% if session.cancelled_because %}</em>{% endif %}
</li>
{% endfor %}
</ul>

{% endblock %}

coaching/templates/coaching/overview.html
{% extends 'base.html' %}

{% block title %}Coaching - {{ season }}{% endblock %}

{% block content %}
<h2>Coaching - {{ season }}</h2>
{% if coached_groups %}
<h3>Groups you are coaching</h3>
<div class="flex-sections">
{% for group in coached_groups %}
    <section class="coaching__group-details">
        <h3>{{ group.group_name }} </h3>
        <p>Meets on {{ group.time }}</p>
        <p>Coached by:
            {% for coach in group.coaches.all %}
                {{ coach }}
            {% endfor %}
        </p>
        <p>
        Participants: {{ group.participants.count }}
        {% if group.trial_set.filter_ongoing.count %}
        <br>
        Current trials: {{ group.trial_set.filter_ongoing.count }}
        </p>
        {% endif %}
        <p><a href="{% url 'coaching:group-report' pk=group.pk group=group.slug %}">View report ></a></p>
    </section>
{% endfor %}
</div>
{% if uncoached_groups %}
<h3>Groups you are NOT coaching</h3>
<div class="flex-sections">
{% for group in uncoached_groups %}
    <section class="coaching__group-details">
        <h3>{{ group.group_name }} </h3>
        <p>Meets on {{ group.time }}</p>
        <p>Coached by:
            {% for coach in group.coaches.all %}
                {{ coach }}
            {% endfor %}
        </p>
        <p>
        Participants: {{ group.participants.count }}
        {% if group.trial_set.filter_ongoing.count %}
        <br>
        Current trials: {{ group.trial_set.filter_ongoing.count }}
        </p>
        {% endif %}
        <p><a href="{% url 'coaching:group-report' pk=group.pk group=group.slug %}">View report ></a></p>
    </section>
{% endfor %}
</div>
{% endif %}
{% else %}
<p>This page is for coaches only at present</p>
{% endif %}

{% if upcoming %}
<h2>Upcoming - {{ upcoming }}</h2>
<h3>Groups you are coaching</h3>
<div class="flex-sections">
{% for group in upcoming_groups %}
    <section class="coaching__group-details">
        <h3>{{ group.group_name }} </h3>
        <p>Meets on {{ group.time }}</p>
        <p>Coached by:
            {% for coach in group.coaches.all %}
                {{ coach }}
            {% endfor %}
        </p>
        <p>
        Participants: {{ group.participants.count }}
        {% if group.trial_set.filter_ongoing.count %}
        <br>
        Current trials: {{ group.trial_set.filter_ongoing.count }}
        </p>
        {% endif %}
        <p><a href="{% url 'coaching:upcoming-group-report' pk=group.pk group=group.slug %}">View report ></a></p>
    </section>
{% endfor %}
</div>
{% if upcoming_uncoached_groups %}
<h3>Groups you are NOT coaching</h3>
<div class="flex-sections">
{% for group in upcoming_uncoached_groups %}
    <section class="coaching__group-details">
        <h3>{{ group.group_name }} </h3>
        <p>Meets on {{ group.time }}</p>
        <p>Coached by:
            {% for coach in group.coaches.all %}
                {{ coach }}
            {% endfor %}
        </p>
        <p>
        Participants: {{ group.participants.count }}
        {% if group.trial_set.filter_ongoing.count %}
        <br>
        Current trials: {{ group.trial_set.filter_ongoing.count }}
        </p>
        {% endif %}
        <p><a href="{% url 'coaching:upcoming-group-report' pk=group.pk group=group.slug %}">View report ></a></p>
    </section>
{% endfor %}
</div>
{% endif %}
{% endif %}

{% endblock content %}